# Generated by Django 4.2.1 on 2023-06-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_services_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service',
            field=models.TextField(max_length=255),
        ),
    ]
